### ISSUE TITLE
[PE-D][Tester A] No error handling for wrong parameters

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T09-3/tp#193]
![image.png](https://raw.githubusercontent.com/RoeReRe/ped/main/files/ca5196f2-63f1-46a3-bdcb-67ccd7ba8b1c.png)

In this case ec should not even be a valid prefix for this command. The command does fail but it detects it as related to email instead.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: RoeReRe/ped#7

**Comment by kohkaijie** [comment]
The issue mentioned above can be attributed to the AddDoctorCommandParser failing to perform checks for extra prefixes not parsed for adding a doctor. As a result the error message thrown will be based on the previous prefix before the incorrect prefix e.g `p/94567183 ec/98887777` will throw an error message for invalid phone number. 

Right now our best way to work around this would be to specify in the UG that users should avoid adding extra prefixes for adding patient and adding doctors, and guiding them on what would happen if they fail to do so. Due to the feature freeze and the specifications of the feature freeze, this is a feature flaw that we are unable to correct. We can include this as a proposed enhancement for future iterations.

**Comment by cmHuang777** [comment]
![image](https://github.com/AY2324S1-CS2103T-T09-3/tp/assets/119959360/6292b2aa-0788-4835-b27d-161bfc35ba64)

May be we can include this point as an extension to the note on command that any extra prefixes that are not used by that command will be disregarded and will be considered as part of the argument of the prefix on the left.
